### PR TITLE
Check filename extension to figure out which compile message to send

### LINKED ISSUE #1: Compile action needs to distinguish between different source files
Hi Baris, thanks a lot for this, it already does mostly what it needs to. But there's still one issue:

If you look at the corresponding [pd-remote.el](https://github.com/agraef/pd-remote/blob/main/pd-remote.el) file, it makes the keybinding language-specific, so with Ctrl+C Ctrl+K it will send a `faustgen2~ compile` command, like your version does, but *only* when you're editing a Faust (.dsp) file. When editing a Lua (in this case .pd_lua) file, it needs to send a `pdluax reload` command for the same keybinding C-C C-K instead.

Is that doable in vscode? Otherwise I'm afraid that you'd have to use two different keybindings in the vscode version, which is less elegant.

### PR DESCRIPTION
**Pull request by agraef**
Fixes #1.

### CODE REVIEW

**Comment by agraef** [comment]
I'm not sure how idiomatic my Typescript code is, also there may be better ways to check the file type of the currently edited file. So feel free to edit this as you see fit.

**Comment by agraef** [comment]
Updated README and bumped version to 1.0.2, for your convenience. After you merged this, can you also please tag the new release and update the package, also in the [marketplace](https://marketplace.visualstudio.com/items?itemName=barisssss.pd-remote-vscode)? Thanks.

**Comment by agraef** [comment]
An update of the ChangeLog on the marketplace might be in order, too.

**Comment by agraef** [comment]
Sneaked a little keybinding change in here, I recently had to change this in pd-remote.el for better compatibility. (The rationale being that Ctrl+g should *never* be bound in Emacs by user stuff since it's the global "abort" key combo. So VS Code should follow suit with its default key bindings.)

**Comment by barisssss** [comment]
Hi Albert,
thanks for the contribution! Looks good to me, however after merging I will modify your Javascript code to comply to Typescript standards. 
The Makefile and build process adjustments are appreciated; that was my first time writing a Makefile, so I'm happy to learn a bit more about that here. :)

Both #1 and #2 are fixed in this PR, so I will merge this one and close PR #3. 
I'll create a new release afterwards.

**Comment by barisssss** [comment]
See commit https://github.com/barisssss/pdRemoteVscode/commit/b44685744f79d82a63b4cfba18c5d00f1fe710d3 for the mentioned TS and formatting fixes.

**Comment by agraef** [comment]
Hi Baris, thanks for fixing my sloppy TS coding, much appreciated. Should be forgivable, hopefully, considering those were the very first few lines of TS I wrote, ever. ;-)

I see that the marketplace was updated, too, works like a charm, thanks!

Meanwhile, upstream pd-remote.el is at 1.1.0 and on its way into [MELPA](https://melpa.org), so this should soon be as convenient to install as your extension.

I've also linked to https://github.com/barisssss/pdRemoteVscode in various places, so that pd-remote users should be able to find it.

Again, thanks for the fun and fruitful collaboration, hope that we can continue that some time. ;-)

**Pull request merged**
